In [2]:
#import libraries
import numpy as np

In [3]:
#working with numpy array
arr = np.array([10,20,30,40,50,60,70])
print("1D array:", arr)
print("\nAverage number:", arr.mean())

1D array: [10 20 30 40 50 60 70]

Average number: 40.0


In [4]:
#indexing
print(arr[3])
print(arr[-2])
print(arr[4])
print(arr[6])

40
60
50
70


In [5]:
#slicing
print(arr[1:6])
print(arr[6:])
print(arr[:7])
print(arr[-6:-1])
print(arr[7:])
print(arr[-1:-6])
print(arr[:9])

[20 30 40 50 60]
[70]
[10 20 30 40 50 60 70]
[20 30 40 50 60]
[]
[]
[10 20 30 40 50 60 70]


In [6]:
#2D array with indexing and slicing
arr2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr2)
print(arr2[0,1])
print(arr2[1, :])
print(arr2[1:2, 2])
print(arr2[2, :2])
print(arr2[1:2, 0:2])
                

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[4 5 6]
[6]
[7 8]
[[4 5]]


In [9]:
#1D to 2D array
arr3 = np.arange(1,13)
reshape = arr3.reshape(4, 3)
print("Array numbers:",arr3)
print("Reshape 1D array into 2D array:\n", reshape)

flatten = reshape.flatten()
print("Flatten array:", flatten)

Array numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape 1D array into 2D array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Flatten array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [10]:
#working with mathematics operation
arr4 = np.array([1,2,3,4,5])
arr5 = np.array([10,20,30,40,50])

#basic math operation
print(arr4 + arr5)
print(arr4 - arr5)
print(arr4 * arr5)
print(arr4 / arr5)

#scaler operation
print(arr5 ** 2)
print(arr5 // 2)
print(arr5 % 3)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[ 100  400  900 1600 2500]
[ 5 10 15 20 25]
[1 2 0 1 2]
